testserver : 
	g++ -o testserver HttpServer_test.cc -lswiftNetCore -lpthread -g

testclient : 
	g++ -o testclient HttpClient_test.cc -lswiftNetCore -lpthread -g


clean :
	rm -f testserver
	rm -f testclient